### PR TITLE
More testsystems

### PR DESCRIPTION
**Pull request by oschulz**
Adds

* Intel i9-13900H   (Thinkpad P1 Gen6)
* [MPCDF Raven](https://www.mpcdf.mpg.de/services/supercomputing/raven) compute node
* [MPCDF Viper](https://www.mpcdf.mpg.de/services/supercomputing/viper) compute node

Raven and Viper login nodes seem to use the same hardware as the compute nodes. (Should I add them too, just in case?)

### CODE REVIEW

**Comment by carstenbauer** [comment]
> Raven and Viper login nodes seem to use the same hardware as the compute nodes. (Should I add them too, just in case?)

If they have the same hardware it doesn't make sense.

**Comment by carstenbauer** [comment]
@oschulz Can you rename the `Intel_i9-13900H` folder → `Intel_i9_13900H` for consistency? Will merge afterwards.

**Comment by oschulz** [comment]
> Can you rename the Intel_i9-13900H folder → Intel_i9_13900H

Whoops, that was a typo - fixed. :-)

**Comment by oschulz** [comment]
@carstenbauer Would you like another test system with 2x AMD EPYC 9654 96-Core , or is that CPU type covered already?

**Comment by carstenbauer** [comment]
> Would you like another test system with 2x AMD EPYC 9654 96-Core , or is that CPU type covered already?

Sure, why not. I don't think it's covered yet.

**Comment by oschulz** [comment]
> Sure, why not. I don't think it's covered yet.

Ok, I'll add it to this PR.

**Comment by oschulz** [comment]
How should I name it (it's the node type of a "nameless" institute-internal cluster)? "Dual_AMD_EPYC-9654" or so?

**Comment by carstenbauer** [comment]
> How should I name it (it's the node type of a "nameless" institute-internal cluster)? "Dual_AMD_EPYC-9654" or so?

If you use an underscore instead of the hyphen I'm fine with this name 👍

**Comment by oschulz** [comment]
I can also add an "NVIDIA_Jetson_Orin_NX_16GB" (mem size included because the 8GB has less cores)?

**Comment by oschulz** [comment]
NB: The Jetson Orin NX is shown to have two sockets (`lscpu` says the same). I think there are two CPU "packages" on the SOC, but they (as well as the GPU cores) are definitely all connected to the same memory.

I found a [block diagram](https://developer-blogs.nvidia.com/wp-content/uploads/2022/09/Block-diagram-of-Jetson-Orin-Nano.png) for the Orin Nano and a [block diagram](https://linuxgizmos.com/files/nvidia_orinsoc_block.jpg) for the AGX Orin - I didn't find one for the Orin NX, but it should be in-between, so to speak.

`Hwloc.sysinfo()` shows

```
Machine (15.03 GB)
    NUMANode (15.03 GB)
    Package L#0 P#0 
        L3 (2.0 MB)
        ...
    Package L#1 P#1 
        ...
    HostBridge 
    ...
 ```
 
and `SysInfo.sysinfo()` says

```
sysinfo()
Hostname: 	batlab-lxarm01
CPU(s): 	2 x Cortex-A78AE
CPU target: 	generic
Cores: 		8 (8 CPU-threads)
NUMA domains: 	1 (8 cores each)

∘ CPU 1: 
	→ 4 cores (4 CPU-threads)
	→ 1 NUMA domain
∘ CPU 2: 
	→ 4 cores (4 CPU-threads)
	→ 1 NUMA domain
```

So two "CPU packages" on a single NUMA domain - I guess that's kinda correct?

**Comment by carstenbauer** [comment]
That's an interesting one. Please add it and I will check/debug later.

**Comment by oschulz** [comment]
> Please add it and I will check/debug later.

Thanks - I've added it to this PR.

**Comment by carstenbauer** [comment]
FYI, now it will look like this:

```julia-repl
julia> sysinfo()
Hostname:       NVIDIA_Jetson_Orin_NX_16GB
CPU(s):         2 x Cortex-A78AE
CPU target:     generic
Cores:          8 (8 CPU-threads)
NUMA domains:   1 (8 cores each)

∘ CPU 1: 
        → 4 cores (4 CPU-threads)
        → 1 NUMA domain (shared with CPU 2)
∘ CPU 2: 
        → 4 cores (4 CPU-threads)
        → 1 NUMA domain (shared with CPU 1)
```

**Comment by oschulz** [comment]
> FYI, now it will look like this

Oh, nice!

I guess with the coming generations of CPU + GPU + (part of the) RAM devices, this is probably not that last we've seen of such "unusual" situations ...

**Comment by oschulz** [comment]
Speaking of more reference system configurations, @williamfgc , could you maybe add Frontier? And @luraess could probably get the Lumi configuration, right?

**Comment by carstenbauer** [comment]
Reminder: The instructions for how to add test systems are [here](https://github.com/carstenbauer/SysInfo.jl#adding-your-system-as-a-test-system). Shouldn't take more than a few minutes.

**Comment by oschulz** [comment]
Do you have access to a Grace-Hopper system @carstenbauer ? If not, @ludgerpaehler might be able to get that reference config.

**Comment by carstenbauer** [comment]
I do have access to A LOT of systems and surely also Grace-Hopper. The thing is, I'm busy with creating/improving these packages right now and help from the community to gather the system information would be appreciated 😉

**Comment by oschulz** [comment]
Then let me also CC @JBlaschke, he might have access to some interesting novel system configurations as well. :-)

**Comment by carstenbauer** [comment]
Side comment: This "fake system" framework is much more useful and stable than I thought. I'm even running Distributed.jl tests for ThreadPinning.jl on the fake systems. And it feels great to see the test suite pass on all of those systems :) (see https://github.com/carstenbauer/ThreadPinning.jl/actions/runs/10297349876/job/28500311017#step:6:149)

**Comment by oschulz** [comment]
Oh, that's a really neat capability!

**Pull request merged**
